# Generated by Django 5.1.2 on 2024-10-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_id', models.CharField(max_length=100)),
                ('sp_id', models.CharField(max_length=100)),
                ('fp_wins', models.JSONField(default=list)),
                ('sp_wins', models.JSONField(default=list)),
                ('num_of_games', models.IntegerField(default=0)),
                ('first_to', models.IntegerField(default=1)),
            ],
        ),
    ]
