version: '3.9'

services:
  app:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTRES_PASSWORD: resuym
  #   ports:
  #     - "5432:5432"